# Generated by Django 4.1.3 on 2022-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='talaba_raqami',
            field=models.IntegerField(default=1, verbose_name='raqami'),
            preserve_default=False,
        ),
    ]
